# Generated by Django 5.0.4 on 2024-10-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='account/no-picture.png', null=True, upload_to='account/user-profile-picture/'),
        ),
    ]
