# Generated by Django 5.0.4 on 2024-05-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutus_text', models.TextField(verbose_name='متن درباره ما')),
                ('content_1', models.TextField(verbose_name='محتوا 1')),
                ('title_1', models.CharField(max_length=25, verbose_name='عنوان 1')),
                ('content_2', models.TextField(verbose_name='محتوا 2')),
                ('title_2', models.CharField(max_length=25, verbose_name='عنوان 2')),
                ('content_3', models.TextField(verbose_name='محتوا 3')),
                ('title_3', models.CharField(max_length=25, verbose_name='عنوان 3')),
                ('address_section', models.TextField(verbose_name='آدرس')),
                ('time_section', models.TextField(verbose_name='تایم کاری')),
                ('phone_section', models.TextField(verbose_name='شماره تلفن')),
            ],
            options={
                'verbose_name': 'محتوا',
                'verbose_name_plural': 'محتواها',
            },
        ),
    ]
