# Generated by Django 5.0.4 on 2024-10-24 06:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_content_4_alter_homepage_aboutus_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'محتوا', 'verbose_name_plural': 'محتوا'},
        ),
        migrations.AlterField(
            model_name='homepage',
            name='aboutus_text',
            field=ckeditor.fields.RichTextField(default='پیش فرض', verbose_name='متن درباره ما'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='address_section',
            field=ckeditor.fields.RichTextField(default='پیش فرض', verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content_1',
            field=ckeditor.fields.RichTextField(default='پیش فرض', verbose_name='محتوا 1'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content_2',
            field=ckeditor.fields.RichTextField(default='پیش فرض', verbose_name='محتوا 2'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content_3',
            field=ckeditor.fields.RichTextField(default='پیش فرض', verbose_name='محتوا 3'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content_4',
            field=ckeditor.fields.RichTextField(default='پیش فرض', verbose_name='محتوا 4'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='phone_section',
            field=ckeditor.fields.RichTextField(default='پیش فرض', verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='time_section',
            field=ckeditor.fields.RichTextField(default='پیش فرض', verbose_name='تایم کاری'),
        ),
    ]
