# Generated by Django 5.0.4 on 2024-10-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_content_4_alter_homepage_aboutus_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'برای تغییر محتوای صفحه اصلی کلیک کنید', 'verbose_name_plural': 'محتوا'},
        ),
    ]
