# Generated by Django 5.0.4 on 2024-10-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'محتوا', 'verbose_name_plural': 'محتوا'},
        ),
    ]
