# Generated by Django 5.0.4 on 2024-04-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام محصول')),
                ('img', models.ImageField(default='shop/no-picture.png', upload_to='shop/product/images/', verbose_name='تصویر محصول')),
                ('quantity', models.IntegerField(default=0, verbose_name='موجودی محصول')),
                ('price', models.IntegerField(verbose_name='قیمت به تومان')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
