# Generated by Django 5.0.4 on 2024-04-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=0, verbose_name="قیمت به تومان"),
        ),
    ]
