# Generated by Django 5.0.4 on 2024-04-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='تصویر محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='static/shop/no-picture', upload_to='shop/product/images/', verbose_name='تصویر محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='تصویر محصول'),
        ),
    ]
