# Generated by Django 5.0.4 on 2024-09-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='reservation//no-picture.png', upload_to='shop/product/images/', verbose_name='تصویر محصول'),
        ),
    ]
