# Generated by Django 5.0.4 on 2024-04-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_quantity_alter_product_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='D:\\w\\blackcut-django-main\\static\\shop\\no-picture.png', upload_to='shop/product/images/', verbose_name='تصویر محصول'),
        ),
    ]
