# Generated by Django 5.0.4 on 2024-04-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_description_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
