# Generated by Django 5.0.4 on 2024-05-22 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=15, verbose_name='نام سرویس')),
                ('is_active', models.BooleanField(choices=[(True, 'فعال'), (False, 'غیرفعال')], default=True, verbose_name='آی این خدمت قابل ارائه است؟')),
            ],
            options={
                'verbose_name': 'سرویس',
                'verbose_name_plural': 'سرویس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(null=True, unique=True)),
                ('finish_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'بازه زمانی',
                'verbose_name_plural': 'بازه های زمانی',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='بازه زمانی')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='آیا این نوبت فعال است')),
                ('is_done', models.BooleanField(blank=True, default=False, null=True, verbose_name='آیا انجام شده است')),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True, verbose_name='آیا پرداخت شده است')),
                ('is_canceled', models.BooleanField(blank=True, default=False, null=True, verbose_name='آیا نوبت لغو شده است؟')),
                ('products', models.ManyToManyField(blank=True, to='shop.product', verbose_name='محصولات انتخابی')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.service', verbose_name='سرویس')),
                ('timeslot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reservation.timeslot', verbose_name='بازه زمانی')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
            },
        ),
    ]
