# Generated by Django 5.0.4 on 2024-04-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='finish_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_done',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='آیا انجام شده است'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='آیا پرداخت شده است'),
        ),
    ]
