# Generated by Django 5.0.4 on 2024-05-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_expired',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='آیا نوبت منقضی شده است؟'),
        ),
    ]
