# Generated by Django 5.0.4 on 2024-04-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_appointment_finish_time_appointment_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='آیا این نوبت فعال است'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='finish_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
