# Generated by Django 5.0.4 on 2024-04-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_appointment_is_active_alter_appointment_finish_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_canceled',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='آیا نوبت لغو شده است؟'),
        ),
    ]
