# Generated by Django 5.0.4 on 2024-09-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('canceled', 'لغو شده'), ('expired', 'منقضی'), ('done', 'انجام شده'), ('paid', 'پرداخت شده')], default='active', max_length=25, verbose_name='وضعیت'),
        ),
    ]
