# Generated by Django 5.0.4 on 2024-04-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_timeslot_remove_appointment_finish_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='finish_time',
            field=models.TimeField(null=True),
        ),
    ]
