# Generated by Django 5.0.4 on 2024-09-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='desc',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='توضیحات سرویس'),
        ),
        migrations.AddField(
            model_name='service',
            name='img',
            field=models.ImageField(default='reservation//no-picture.png', upload_to='reservation/service/images/', verbose_name='تصویر سرویس'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'فعال'), (False, 'غیرفعال')], default=True, verbose_name='وضعیت فعال بودن'),
        ),
    ]
