# Generated by Django 5.0.4 on 2024-04-18 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_alter_timeslot_finish_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'نوبت', 'verbose_name_plural': 'نوبت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'سرویس', 'verbose_name_plural': 'سرویس\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'بازه زمانی', 'verbose_name_plural': 'بازه های زمانی'},
        ),
    ]
