# Generated by Django 5.0.4 on 2024-09-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_service_desc_service_img_alter_service_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dayoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'روز تعطیل',
                'verbose_name_plural': 'روزهای تعطیل',
            },
        ),
    ]
