# Generated by Django 5.0.4 on 2024-04-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_alter_appointment_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(verbose_name='بازه زمانی'),
        ),
    ]
