# Generated by Django 5.0.4 on 2024-10-01 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_dayoff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'تایم', 'verbose_name_plural': 'تایم ها'},
        ),
    ]
