# Generated by Django 5.0.4 on 2024-04-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(null=True, unique=True),
        ),
    ]
