# Generated by Django 5.0.4 on 2024-10-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_alter_timeslot_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('done', 'انجام شده'), ('paid', 'پرداخت شده'), ('expired', 'منقضی'), ('canceled', 'لغو شده')], default='active', max_length=25, verbose_name='وضعیت'),
        ),
    ]
