# Generated by Django 5.0.4 on 2024-04-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_alter_timeslot_start_time'),
        ('shop', '0007_alter_product_img_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='shop.product', verbose_name='محصولات انتخابی'),
        ),
    ]
