# Generated by Django 5.0.4 on 2024-10-02 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_alter_appointment_status'),
        ('shop', '0005_alter_product_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'done', 'paid'])), fields=('date', 'timeslot', 'service'), name='unique_appointment'),
        ),
    ]
