# Generated by Django 5.0.4 on 2024-10-23 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_appointment_unique_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_expired',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_paid',
        ),
    ]
